# Generated by Django 5.2.1 on 2025-05-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_network_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=300)),
                ('total_bytes_up', models.BigIntegerField(default=0)),
                ('total_bytes_down', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
