# Generated by Django 5.2.1 on 2025-05-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_networkstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkstat',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='networkstat',
            name='rx_bytes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkstat',
            name='tx_bytes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkstat',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='networkstat',
            name='ssid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networkstat',
            name='total_bytes_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='networkstat',
            name='total_bytes_up',
            field=models.IntegerField(default=0),
        ),
    ]
